name: "Go WakaTime Readme"
description: "Go GitHub Action that adds Coding time statistics to your README"

runs:
  using: composite
  steps:
    - run: ls
      shell: bash
    - run: go run ./
      shell: bash
